// // Autogenerated using the Scaffolder feature in wawa.Editors.
// // Code generated by wawa.Editors is in public domain.
// // Source: https://github.com/Emik03/wawa
//
// using System;
// using UnityEngine;
// using Wawa.Modules;
// using Random = UnityEngine.Random;
//
// /// <summary>On the Subject of <see cref="Needy"/>.</summary>
// public sealed class Needy : ModdedModule
// {
//     protected override void OnActivate()
//     {
//         Log("Hello, World! ma o, toki!");
//     }
// }
